### ISSUE TITLE
System Not Working

### ISSUE THREAD

**Issue by PerfectNoob13** [Sublivion/Rocket-System#2]
**Describe the bug**
The rocket system simply just won't work, I don't know why to be honest.
**To Reproduce**
1. Insert the model
2. Place it in ServerScriptService
3. Put in the example rocket along with the launch pad and base (Make sure it's only the launch pad and base, nothing in them)
4. Test in studio

**Expected behavior**
It doesn't work.

**Desktop (please complete the following information):**
 - Windows 10

**Comment by Sublivion** [comment]
Will be fixed in next version
